services:
  nautilus:
    build:
      context: .
      dockerfile: Dockerfile
    image: nautilus:latest
    container_name: nautilus
    env_file:
      - .env
    ports:
      - "3069:3069"
    volumes:
      - nautilus-config:/data
    restart: unless-stopped

volumes:
  nautilus-config:
    driver: local
